### ISSUE TITLE
Some steps are failing during AWS deployment

### ISSUE THREAD

**Issue by rachelcarmena** [arrow-kt/try.arrow-kt.io#19]
After the last change #18 I realized about these errors during the deployment:

```
cp: cannot create regular file 'docker/frontend/conf/README': Permission denied
cp: cannot create regular file 'docker/frontend/conf/cert.pem': Permission denied
cp: cannot create regular file 'docker/frontend/conf/chain.pem': Permission denied
cp: cannot create regular file 'docker/frontend/conf/fullchain.pem': Permission denied
cp: cannot create regular file 'docker/frontend/conf/privkey.pem': Permission denied
```
```
> Unable to delete directory: /home/ubuntu/try.arrow-kt.io/kotlin.web.demo.backend/build/libs/WebDemoBackend.war
```
```
> Cannot write to file '/home/ubuntu/try.arrow-kt.io/kotlin.web.demo.backend/build/libs/WebDemoBackend.war' specified for property 'archivePath' as it is a directory.
```

They also happen during the daily deployment.

cc: @calvellido

**Comment by rachelcarmena** [comment]
Thank you so much @franciscodr :tada: They are fixed when updating file permissions :raised_hands:

**Comment by calvellido** [comment]
Hey!  tried to had a look at this but wasn't able, do we know if those permissions respawn on each deploy?

**Comment by rachelcarmena** [comment]
> Hey! tried to had a look at this but wasn't able, do we know if those permissions respawn on each deploy?

:raised_hands: It was fixed by @franciscodr on Friday and it's working OK since then :clap:
